name: LofiNest Live
on:
  workflow_dispatch:      # Button se manually start karne ke liye
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein Automatic Restart

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start YouTube Stream
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          # Jab upload khatam ho, to uska MP3 link yahan paste karna
          # Agar abhi test karna hai to niche wala link use kar lo (Temporary)
          AUDIO_URL: "https://archive.org/download/StreamBeatsLoFi/Harris%20Heller%20-%20StreamBeats%20-%20Lo-Fi%20-%2001%20White%20Noise.mp3"
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 \
          -thread_queue_size 512 -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          -stream_loop -1 -i "$AUDIO_URL" \
          -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -map 0:v:0 -map 1:a:0 \
          -f flv -flvflags no_duration_filesize "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY"
